on:
  workflow_dispatch:
  
name: Bad Practice Secret Scrapper

jobs:
  scrape_secret:
    runs-on: ubuntu-latest
    steps:
      - name: this is a terrible idea
        run: echo ${{secrets.ORG_ACTION_TEST_SECRET}} | sed 's/./& /g'
      - name: bad idea on repo level
        run: echo ${{secrets.REPO_TEST_ACTIONS_SECRET}} | sed 's/./& /g'
